import './globals.css'
import type { Metadata } from 'next'
import React from "react";
import Header from '../components/Header';

export const metadata: Metadata = {
  title: 'Google Shop Scraper',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="">
        <main>
          <Header />
          {children}
        </main>
      </body>
    </html>
  )
}
